spring:
  application:
    name: portfolio-api

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: "aslan47123"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

app:
  jwt:
    secret: "bXktcG9ydGZvbGlvLWp3dC1zZWNyZXQta2V5LTIwMjYtZm9yLWRldmVsb3BtZW50"
    expiration: 3600000